server:
    port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/anky_sentence
    username: test
    password: hoge00
    driverClassName: com.mysql.jdbc.Driver
mail:
    host: smtp.gmail.com
    port: 587
    username: hogehoge@hogehoge.com
    password: hogehoge
settings:
    url: http://localhost:8080
    activatePath: /user/activate/
    remindPath: /user/remind/
    fromMail: ensyuritu3@gmail.com
    systemName: anly-sentence
