server:
    port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/anky_sentence?serverTimezone=JST
    username: test
    password: hoge00
    driverClassName: com.mysql.cj.jdbc.Driver
mail:
    host: smtp.mailtrap.io
    port: 2525
    username: b8d337572a6fe7
    password: 38950e2b3918b2
settings:
    url: http://localhost:8080
    activatePath: /user/activate/
    remindPath: /user/remind/
    fromMail: f37f55677b-d2241c@inbox.mailtrap.io
    systemName: anly-sentence
mybatis.configuration.mapUnderscoreToCamelCase: true
